<a href="https://colab.research.google.com/github/kevinrupertpoint/pythonFromGoogleDrive/blob/master/numpyTestOnColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
print ("hello ")
i = 2+3
print(i)
i = 2
print("me")

hello 
5
me


In [0]:
# Create a 2d array from a list of lists
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)
arr2d
# Create a float 2d array
arr2d_f = np.array(list2, dtype='float')
arr2d_f
# Convert to int then to str datatype
arr2d_f.astype('int').astype('str')

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U21')

In [0]:
import numpy as np
list1 = [0,1,2,3,4]
arrld = np.array(list1)
print(arrld)
print (type(arrld))

In [0]:
# Create an object array to hold numbers as well as strings
arr1d_obj = np.array([1, 'a'], dtype='object')
arr1d_obj

array([1, 'a'], dtype=object)

In [0]:
# Create a 2d array with 3 rows and 4 columns
import numpy as np
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2
lst1 =arr2.tolist()
print(lst1)
# shape
print('Shape: ', arr2.shape)
# dtype
print('Datatype: ', arr2.dtype)
# size
print('Size: ', arr2.size)
# ndim
print('Num Dimensions: ', arr2.ndim)
b = arr2 > 4
print(b);
#reverse only row position
d = arr2 [::-1,]
print(d);
#reverse both dimensions
e = arr2[::-1,::-1]
print(e);
#insert missing value and indefinite value
e[1,2]=np.nan
e[1,1]=np.inf
print(e)
# Replace nan and inf with -1. Don't use arr2 == np.nan
missing_bool = np.isnan(e) | np.isinf(e)
e[missing_bool] = -1  
print(e)
# mean, max and min
print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())
# Row wise and column wise min
print(arr2)
print("Column wise minimum: ", np.amin(arr2, axis=0))
print("Row wise minimum: ", np.amin(arr2, axis=1))
# Cumulative Sum
g = np.cumsum(arr2)
print(g)
# Convert to 'int' datatype
print("convert to integer")
arr2.astype('int')
print(arr2)# Create a boolean array
arr2d_b = np.array([1, 0, 10], dtype='bool')
print(arr2d_b)
# Create an object array to hold numbers as well as strings
arr1d_obj = np.array([1, 'a'], dtype='object')
print(arr1d_obj)
# Reshape a 3x4 array to 4x3 array
print("reshape demo")
arr3  = arr2
#reshape does not change the shape of arr3
arr4 = arr3.reshape(4, 3)
print(arr2)
print(arr3)
print(arr4)
print(arr3.shape)
print(arr4.shape)

[[1.0, 2.0, 3.0, 4.0], [3.0, 4.0, 5.0, 6.0], [5.0, 6.0, 7.0, 8.0]]
Shape:  (3, 4)
Datatype:  float64
Size:  12
Num Dimensions:  2
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[5. 6. 7. 8.]
 [3. 4. 5. 6.]
 [1. 2. 3. 4.]]
[[8. 7. 6. 5.]
 [6. 5. 4. 3.]
 [4. 3. 2. 1.]]
[[ 8.  7.  6.  5.]
 [ 6. inf nan  3.]
 [ 4.  3.  2.  1.]]
[[ 8.  7.  6.  5.]
 [ 6. -1. -1.  3.]
 [ 4.  3.  2.  1.]]
Mean value is:  3.5833333333333335
Max value is:  8.0
Min value is:  -1.0
[[ 1.  2.  3.  4.]
 [ 3. -1. -1.  6.]
 [ 5.  6.  7.  8.]]
Column wise minimum:  [ 1. -1. -1.  4.]
Row wise minimum:  [ 1. -1.  5.]
[ 1.  3.  6. 10. 13. 12. 11. 17. 22. 28. 35. 43.]
convert to integer
[[ 1.  2.  3.  4.]
 [ 3. -1. -1.  6.]
 [ 5.  6.  7.  8.]]
[ True False  True]
[1 'a']
reshape demo
[[ 1.  2.  3.  4.]
 [ 3. -1. -1.  6.]
 [ 5.  6.  7.  8.]]
[[ 1.  2.  3.  4.]
 [ 3. -1. -1.  6.]
 [ 5.  6.  7.  8.]]
[[ 1.  2.  3.]
 [ 4.  3. -1.]
 [-1.  6.  5.]
 [ 6.  7.  8.]]
(3, 4)
(4, 3)


In [0]:
# Create a 2d array with 3 rows and 4 columns
import numpy as np
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='int')
print(arr2)
# Changing the flattened array does not change parent
b1 = arr2.flatten()  
b1[0] = 100  # changing b1 does not affect arr2
print(arr2)
print(b1)
# Changing the raveled array changes the parent also.
b2 = arr2.ravel()  
b2[0] = 101  # changing b2 changes arr2 also
print(arr2)
print(b2)

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]
[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]
[100   2   3   4   3   4   5   6   5   6   7   8]
[[101   2   3   4]
 [  3   4   5   6]
 [  5   6   7   8]]
[101   2   3   4   3   4   5   6   5   6   7   8]
